name: Build & Release MATLAB Toolbox

on:
  release:
    types: [published]

jobs:  
  release-toolbox:
    if: github.repository == 'TopoToolbox/ttminvoellmy'
    runs-on: ubuntu-latest

    permissions:
      contents: write   # required to update release      
    steps:
      - name: Check out repository
        uses: TopoToolbox/actions/checkout@main

      - name: Set up MATLAB
        uses: TopoToolbox/actions/setup-matlab@main
        with:
          release: r2025a
          cache: true
          
      - name: Build toolbox
        uses: TopoToolbox/actions/run-build@main
        with:
          tasks: package

      - name: Upload toolbox artifact
        uses: TopoToolbox/actions/upload-artifact@main
        with:
          name: toolbox
          path: release/ttminvoellmy.mltbx

      - name: Upload toolbox assets
        shell: bash
        run: gh release upload --repo $GITHUB_REPOSITORY $TAG release/ttminvoellmy.mltbx
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.event.release.tag_name }}
